"Resource/ui/main_menu/OptionsDialog.res"
{
	"CTFOptionsDialog"
	{
		"ControlName"			"EditablePanel"
		"fieldName"				"CTFOptionsDialog"
		"xpos"					"cs-0.5"
		"ypos"					"cs-0.5"
		"wide"					"500"
		"tall"					"400"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"   	"0"
		"border"				"TFFatLineBorder"
	}
	
	
	"OK"
	{
		"ControlName"	"CTFButton"
		"fieldName"		"OK"
		"xpos"			"300"
		"ypos"			"370"
		"zpos"			"2"
		"wide"			"50"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"command"		"Ok"	
		"paintbackground"   "0"
		"labelText" 		"#GameUI_OK"
		"textAlignment"		"center"
		"font"				""
		"border_default"	"AdvRoundedButtonDefault"
		"border_armed"		"AdvRoundedButtonArmed"
		"border_depressed"	"AdvRoundedButtonDepressed"
	}
	
	"Cancel"
	{
		"ControlName"	"CTFButton"
		"fieldName"		"Cancel"
		"xpos"			"355"
		"ypos"			"370"
		"zpos"			"2"
		"wide"			"60"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"paintbackground"   "0"
		"command"		"vguicancel"
		"labelText" 		"#GameUI_Cancel"
		"textAlignment"		"center"
		"font"				""
		"border_default"	"AdvRoundedButtonDefault"
		"border_armed"		"AdvRoundedButtonArmed"
		"border_depressed"	"AdvRoundedButtonDepressed"
	}	
	
	"Apply"
	{
		"ControlName"	"CTFButton"
		"fieldName"		"Apply"
		"xpos"			"420"
		"ypos"			"370"
		"zpos"			"2"
		"wide"			"60"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"0"
		"paintbackground"   "0"
		"command"		"Apply"
		"labelText" 		"#GameUI_Apply"
		"textAlignment"		"center"
		"font"				""
		"border_default"	"AdvRoundedButtonDefault"
		"border_armed"		"AdvRoundedButtonArmed"
		"border_depressed"	"AdvRoundedButtonDepressed"
	}

	"Defaults"
	{
		"ControlName"		"CTFButton"
		"fieldName"			"Defaults"
		"xpos"				"20"
		"ypos"				"370"
		"wide"				"80"
		"tall"				"20"
		"visible"			"0"
		"enabled"			"1"
		"paintbackground"   "0"
		"Command"			"DefaultsOK"
		"labelText" 		"#GameUI_UseDefaults"
		"textAlignment"		"center"
		"font"				""
		"paintbackground"   "0"
		"border_default"	"AdvRoundedButtonDefault"
		"border_armed"		"AdvRoundedButtonArmed"
		"border_depressed"	"AdvRoundedButtonDepressed"
	}
	
	
	"optionsbutton"
	{
		"ControlName"		"CAdvTabs"
		"fieldName"			"optionsbutton"
		"xpos"				"cs-0.5"
		"ypos"				"20"
		"paintbackground"   "0"
		"zpos"				"6"
		"wide"				"420"
		"tall"				"25"
		"visible"			"1"
		"enabled"			"1"
		"bordervisible"		"0"	
		"proportionaltoparent"		"1"

		"AdvButton"
		{
			"ControlName"					"CTFButton"
			"fieldName"						"AdvButton"
			"visible"						"1"
			"enabled"						"1"
			"bordervisible"					"1"	
			"paintbackground"   			"0"
			"command"						"newoptionsadv"

			"labelText"						"#GameUI_Multiplayer"
			"font"							"HudFontSmall"
			"textAlignment"					"center"	
			
			"xshift" 						"0"
			"yshift"						"0"
			"stayselectedonclick"			"1"
			"border_default"				"AdvLeftButtonDefault"
			"border_armed"					"AdvLeftButtonArmed"
			"border_depressed"				"AdvLeftButtonDepressed"
			"selectedFgColor_override"		"255 255 180 255"
		}
		"MouseButton"
		{
			"ControlName"					"CTFButton"
			"fieldName"						"MouseButton"
			"visible"						"1"
			"enabled"						"1"
			"bordervisible"					"1"	
			"paintbackground"   			"0"
			"command"						"newoptionsmouse"

			"labelText"						"#GameUI_Mouse"
			"font"							"HudFontSmall"
			"textAlignment"					"center"	
			
			"xshift" 						"0"
			"yshift"						"0"
			"stayselectedonclick"			"1"
			"border_default"				"AdvSquareButtonDefault"
			"border_armed"					"AdvSquareButtonArmed"
			"border_depressed"				"AdvSquareButtonDepressed"
			"selectedFgColor_override"		"255 255 180 255"
		}
		"KeyboardButton"
		{
			"ControlName"					"CTFButton"
			"fieldName"						"KeyboardButton"
			"visible"						"1"
			"enabled"						"1"
			"bordervisible"					"1"	
			"paintbackground"   			"0"
			"command"						"newoptionskeyboard"

			"labelText"						"#GameUI_Keyboard"
			"font"							"HudFontSmall"
			"textAlignment"					"center"	
			
			"xshift" 						"0"
			"yshift"						"0"
			"stayselectedonclick"			"1"
			"border_default"				"AdvSquareButtonDefault"
			"border_armed"					"AdvSquareButtonArmed"
			"border_depressed"				"AdvSquareButtonDepressed"
			"selectedFgColor_override"		"255 255 180 255"
		}
		"AudioButton"
		{
			"ControlName"					"CTFButton"
			"fieldName"						"AudioButton"
			"visible"						"1"
			"enabled"						"1"
			"bordervisible"					"1"	
			"paintbackground"   			"0"
			"command"						"newoptionsaudio"

			"labelText"						"#GameUI_Audio"
			"font"							"HudFontSmall"
			"textAlignment"					"center"	
			
			"xshift" 						"0"
			"yshift"						"0"
			"stayselectedonclick"			"1"
			"border_default"				"AdvSquareButtonDefault"
			"border_armed"					"AdvSquareButtonArmed"
			"border_depressed"				"AdvSquareButtonDepressed"
			"selectedFgColor_override"		"255 255 180 255"
		}
		"VideoButton"
		{
			"ControlName"					"CTFButton"
			"fieldName"						"VideoButton"
			"visible"						"1"
			"enabled"						"1"
			"bordervisible"					"1"	
			"paintbackground"   			"0"
			"command"						"newoptionsvideo"

			"labelText"						"#GameUI_Video"
			"font"							"HudFontSmall"
			"textAlignment"					"center"	
			
			"xshift" 						"0"
			"yshift"						"0"
			"stayselectedonclick"			"1"
			"border_default"				"AdvSquareButtonDefault"
			"border_armed"					"AdvSquareButtonArmed"
			"border_depressed"				"AdvSquareButtonDepressed"
			"selectedFgColor_override"		"255 255 180 255"
		}
		"VGUIButton"
		{
			"ControlName"					"CTFButton"
			"fieldName"						"VGUIButton"
			"visible"						"1"
			"enabled"						"1"
			"bordervisible"					"1"	
			"paintbackground"   			"0"
			"command"						"newoptionsvgui"

			"labelText"						"VGUI"
			"font"							"HudFontSmall"
			"textAlignment"					"center"	
			
			"xshift" 						"0"
			"yshift"						"0"
			"stayselectedonclick"			"1"
			"border_default"				"AdvRightButtonDefault"
			"border_armed"					"AdvRightButtonArmed"
			"border_depressed"				"AdvRightButtonDepressed"	
			"selectedFgColor_override"		"255 255 180 255"
		}
	}
}
