"Resource/UI/HudBuyTargetID.res"
{	
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"130"
		"tall"			"65"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"image"			"../hud/medic_charge_red_bg"	
		"teambg_2"		"../hud/medic_charge_red_bg"
		"teambg_3"		"../hud/medic_charge_blue_bg"
		"teambg_4"		"../hud/medic_charge_green_bg"
		"teambg_5"		"../hud/medic_charge_yellow_bg"
	}
	"ItemName"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemName"
		"xpos"			"cs-0.475"
		"ypos"			"15"
		"zpos"			"3"		
		"wide"			"105"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"
		"labelText"		"%name%"
		"font"			"HudFontSmall"
		"proportionaltoparent"		"1"
	}
	"ItemCost"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemCost"
		"xpos"			"cs-0.475"
		"ypos"			"28"
		"zpos"			"3"		
		"wide"			"105"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"
		"labelText"		"%cost%"
		"font"			"HudFontSmall"
		"proportionaltoparent"		"1"
	}
}